spring.application.name=MiniSearchEngine

# config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/se330
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
###

#config auth
mini-search.jwt.base64-secret=CQxHhfO1ZPMHDzW1SNlKuRoq+aXNDI2bvdOliVPzEQJDFA+eyTLOSljP+q9wIQCGXGPUIHAc+A07VzEnc9XbJg==
mini-search.jwt.access-token-validity-in-seconds=864000
mini-search.jwt.refresh-token-validity-in-seconds=864000
mini-search.cors.allowed-origins=http://localhost:5173

#re-config dev tool
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#config actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true
